sudo: false
language: node_js
node_js:
- '8.10'
script: npm run build && npm test
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: s3
  access_key_id: AKIAJHKZXRZA2Q2ZRHWQ
  secret_access_key:
    secure: hrkdE0LNfVQ9/1hID/lPmttEPywK1u3QdgrfHHDzU9Gf6g72smyF8B3qHp0RWfKZRNFDUuR+cTXCYQ1l8W3OaMQXj9kisA+hke6zl1+MhjIWrwzNqlacaFxbCMPEQAuOQuaFzZyetLdPKwq+NWkLGq5DIvqX+gUxSrPqXCczz+Ni78kovyCM76bEOvSjY2jOW3aHvY+uVqZUfoP2b7mdWmAmY3s51hZB/YvWNi2ODQBrzIGkywldW7J2HOSydV54HtLG27p90I71Gw8uxx4YjMsRRYtyVMTh+TEtHb/s8TQVC1lkUTOJJo6uejgJNRcrxgLvuIxP+7w2NZ1l+n8NZgCFUjG7omA6KTO3Ewe+7P0no+rACCcrsxonkhZmFBAT2e6uKl3OWLLdPcKOZ0grSfZDd2s1llHUMbXsAeYgI79DpAiiApx3ESn7bzcUX1NuZbhLy34NHSI5nwj5NL/Zqt0mdq8fwQ6wjm2yje9NxjLGAjhhQxxNOwc869INAMKDFnS7KAO+bp8AWh8PGi3Y+xXMibRQAPm+UlpsCL2b3aDxFAwHiVV3VbjMxY2nnnGk9G6u6eWh0Y6pPBO4pP97lgMtArbRBi5zeOAo7iiqvosytRFFUjMJT9KyzRcURLuKTtnlfCBh6cDNvob6Xq9Nbeox2l+XAM7TIXQ7gv6YwIg=
  bucket: dream-skill
