sudo: false
language: node_js
node_js:
- '8.10'
script: npm run build && npm test
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- ls
- zip -r ${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_BUILD_NUMBER}.zip ${REPO}
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  file: ${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_BUILD_NUMBER}.zip
  bucket: dream-skill
