sudo: false
language: node_js
node_js:
- '8.10'
script: npm run build && npm test
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: dream-skill
