sudo: false
language: node_js
node_js:
- '8.10'
script: npm run build && npm test
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- zip -r ${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_BUILD_NUMBER}.zip .
- mkdir upload
- mv ${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_BUILD_NUMBER}.zip upload/
deploy:
  provider: s3
  skip_cleanup: true
  local_dir: upload
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: dream-skill
