sudo: false
language: node_js
node_js:
- '8.10'
script: npm run build && npm test
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: s3
  access_key_id: AWS Key
  secret_access_key:
    secure: xjaPbWgbRKS3r4YH1nbGks7V/u33Xq3tPGV9jlAdRDmoepld+LyotqMXJJQCopy/SSXW5/B4darryLuYd50HLInSdD8PbVqI/vmML9+CmY14DtP71tq6nMCxbRZSLFGDRiXBDajWVKtBCddoi2hZd9WZRTFTL2K2HUpjgflyQkU35OJSn+zk1SHzabg2dtZvKyfi2OrDbemMvzbIN4lkoF6YrouNJ8Q8WyhKcdAeL+wKLvkMgKXDyywizXKSJk1VAfF2yKO57CXbdlvbBzShYM9zoErSoWAq/rBIlyxznIqFrTYRrkcKbjnm2MV43UZM8D5x+0M/2eH7Q4C7hffPUbm4HqMzv/4Y209RpgEffhWZ2j7WF6jyL9L3p84uHLRK5KEGftCK/Xgmw9ULS4XVJfcGCEtvUZCC8jfmZ1Aknqc4UTRUAzDiHVe8qs3FbngZvKN3oOaCNVSYRqAp0WbuPi7NzVHBqFWz5AKiWtZC3pyosgog+mb1LSr3MRt8qFeCuH6kVh1MuY2qqikX48A+DUjroiOnwha0JSmDRGXCupGScYhINNWZ4FdJOnyheH7piidNNWk/qM1ismv1M71E1MgzQ5Si/9qyVnacLBsQkGasuFd284OX8ml3woLKuzjM0fTF4QL19KZ8y5p69xtEUSxC+LNcqcxxKVeaLzXMbt8=
  bucket: dream-skill
