sudo: false
language: node_js
node_js:
- '8.10'
script: npm run build && npm test
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: s3
  access_key_id: AKIAJHKZXRZA2Q2ZRHWQ
  secret_access_key:
    secure: 0G+pZ+UJ/JvppFk+O2xaJatRwJFZDiHnGq+XvHltuodRzUzYWUrFiH/OQZAdrlPCfp5FyKDtTJCU6QRa8gSN4eghLlOR9nmhG9bNj+ZUhRjCdddCH3888Gua2wBQbSVpwalx7N9lOuXgUV+HWm4KfVwmLPvmtFpK0epR7BLYoWNRNEw0XssHl0SVzyrmHba5NHUHyx7h5YgBkHtOAc/R66ybOkKyIciZ0x3ErcV53oTGmrll4KlQ7HU3ewLPoaOY+Y0N1cyo8nBwWjmEg+8rLVcJn+OnE3iZuX2nIsKTx8urQzpximzcCbdaGbDPAAbCAozM/eV1muxmIvOuHnfUDtUc/CeMH0XtOL2oJoM68TOOf1QXYm7CXlX+ghzF9J3lSaRgqT2Bap8b5H4vVuGIw2T5PoTYwOtV/jdyAvMlp1RQTIbDLb//6KF1ysrBTPS4W4DSD1FW45N2X1kCMMEBcVojaOPusI+jw/UeQ2ftziK3TbpHro1bfWvTxwKUs1rZQQrfDRUkjxKJrn4XMXfMwB0uraWU3tG6NP6jN2e+oBTg9M8ZrBWvIEn24vvHMaKKzcdEXgiYBZ4bjtbDzt9o1e5kglMyQcpasVHcbhJQNP83lbwu0Oq/gRSXhDqVwJNw9iJa9MpEhEP4ObjBaRKYM/dIqnRVqtPWrxLXjzfT/Z4=
  bucket: dream-skill
